scan_timeout = 100

[custom.jj]
command = "jj-starship"
when = "jj-starship detect"

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_status]
disabled = true

[kubernetes]
disabled = false
contexts = [
  { context_pattern = "orbstack", style = "green bold" },
  { context_pattern = ".*", style = "red bold" },
]
