#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Matt Thorning"
email = "matt.thorning@grafana.com"

[revset-aliases]
'stack' = 'main@origin | main | ancestors(bookmarks(), 2) | @'
"context" = 'main..@ | main'

[aliases]
context = ["log", "-r", "context"]
stack = ["log", "-r", "stack"]
