#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Matt Thorning"
email = "matthewthorning@gmail.com"

[[--scope]]
--when.hostnames = ["Matts-GMBP.local"]
[--scope.user]
email = "matt.thorning@grafana.com"

[[--scope]]
--when.hostnames = ["Matts-GMBP.local"]
--when.repositories = ["~/dotfiles"]
[--scope.user]
email = "matthewthorning@gmail.com"

[revset-aliases]
'stack' = 'main@origin | main | ancestors(bookmarks(), 2) | @'
"context" = 'main..@ | main'

[aliases]
ctx = ["log", "-r", "context"]
stack = ["log", "-r", "stack"]
